services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "${DOCKER_PORT:-8002}:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
